### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by XxJustPlayxX** [CraftPig/sweps_scpsl_consumables#1]
i would like to report for a bug. majority of the model/sweps are invincible and tiny bit of it is visible. i also tried to put it in my addon folder but also not worked out. hope you can fix it. this is nice addon ngl

![20240817130907_1](https://github.com/user-attachments/assets/861361df-a38e-4591-98d6-c4651f63dee8)
![20240817130912_1](https://github.com/user-attachments/assets/ce1fb52b-97a4-4b7a-b3b4-3ea97f2873fa)
![20240817130916_1](https://github.com/user-attachments/assets/37c2e18a-36b0-437e-a3ef-69e271845011)
![20240817130920_1](https://github.com/user-attachments/assets/7c68696a-2121-4476-911a-a2913d32558f)
![20240817130924_1](https://github.com/user-attachments/assets/9b9beee8-05c6-4c67-ba06-c9f83d79cfaf)
![20240817130930_1](https://github.com/user-attachments/assets/46c0c464-b9ab-4724-8220-4d3c0b028324)
![20240817130821_1](https://github.com/user-attachments/assets/1e15eba0-6767-4600-84c2-1afcc8fd456d)
![20240817130903_1](https://github.com/user-attachments/assets/9053aa1d-5e4c-4bb6-87c6-d0dbced41e6d)

**Comment by XxJustPlayxX** [comment]
im forgot something btw when in 3rd person mod the sweps are fully visible

**Comment by CraftPig** [comment]
There is a bodygroup modifier baked into the medkits sequence, so it hides it mid healing animation. So technically this shouldnt happen if you dont interupt the medkit anims and or get it fixed if you consume another medkit.

I will probably just remove the modifier though due it it being not necessary.

**Comment by Mettadoxx** [comment]
this happens to me aswell whenever i use the eft weapons its annoying that i cant see the medkits

**Comment by ReconCoyote978** [comment]
yeah I have the same problem as Mettadoxx every now and then, perhaps remove the invisibility modifier?

**Comment by CraftPig** [comment]
If this still occurs regularly, could you describe what to do to replicate the effect?

**Comment by Mettadoxx** [comment]
> If this still occurs regularly, could you describe what to do to replicate the effect?

i'll try to record whats occuring

**Comment by Mettadoxx** [comment]
the requirements are there
![20240831161030_1](https://github.com/user-attachments/assets/ab9814fa-23f9-4a46-9e43-3d0584d71cf8)

**Comment by Mettadoxx** [comment]
![20240831171030_1](https://github.com/user-attachments/assets/4e81ab89-984e-42c5-ab58-476e8da3f0db

**Comment by Mettadoxx** [comment]
![20240831171030_1](https://github.com/user-attachments/assets/fbfe1705-176f-4b17-aae3-851dcfce775a)
only happens if i have the eft weapons

**Comment by ReconCoyote978** [comment]
Yes, it happens too, when I switch to medkits from using ARC-9 EFT weapons, but the whole medkits but the zipper are invisible instead of just the bandage and zipper. Sometimes quick switching, to a different weapon or spawning a new weapon and switching back alleviate the problem. I don't exactly remember the order, but I will try to find a repeatable method next time I play Gmod

**Comment by ReconCoyote978** [comment]
I don't exactly remember the order, but I will try to find a repeatable method next time I play Gmod

**Comment by ReconCoyote978** [comment]
Okay, yeah it seems pretty consistent.

To replicate method:

Upon spawn: spawn and equip any medkit, the model will be fine.

The spawn and equip any ARC9-EFT gun, for my test I chose the Remington SASS.

Quick switch or standard switch back to the medkit and it'll be a floating zipper and bandaid.

**Comment by Aaronek10** [comment]
> Okay, yeah it seems pretty consistent.
> 
> To replicate method:
> 
> Upon spawn: spawn and equip any medkit, the model will be fine.
> 
> The spawn and equip any ARC9-EFT gun, for my test I chose the Remington SASS.
> 
> Quick switch or standard switch back to the medkit and it'll be a floating zipper and bandaid.

Attachment system in ARC9 is causing this issue. Sadly we can't do anything about it.

**Comment by Mettadoxx** [comment]
> > Okay, yeah it seems pretty consistent.
> > To replicate method:
> > Upon spawn: spawn and equip any medkit, the model will be fine.
> > The spawn and equip any ARC9-EFT gun, for my test I chose the Remington SASS.
> > Quick switch or standard switch back to the medkit and it'll be a floating zipper and bandaid.
> 
> Attachment system in ARC9 is causing this issue. Sadly we can't do anything about it.

damn

**Comment by ReconCoyote978** [comment]
> > Okay, yeah it seems pretty consistent.
> > To replicate method:
> > Upon spawn: spawn and equip any medkit, the model will be fine.
> > The spawn and equip any ARC9-EFT gun, for my test I chose the Remington SASS.
> > Quick switch or standard switch back to the medkit and it'll be a floating zipper and bandaid.
> 
> Attachment system in ARC9 is causing this issue. Sadly we can't do anything about it.

Is the attachment system of ARC9 EFT exclusively, or ARC9 entirety? If so what technical explanation for the conflict so I can take it up with Darsu?

**Comment by Aaronek10** [comment]
Entire Arc9 attachment system.

I can't describe what exacly is happening from code side, but i think ARC9 hides/disables something when weapon is getting switched causing this issue, mainly when weapon have any attachment installed on it.

**Comment by ReconCoyote978** [comment]
Okay, I'll see if I can take this issue to Darsu, but I was wondering, couldn't you add code that forces said visibility on when we equip the meds?
