### ISSUE TITLE
Parts of or entire items will just disappear (Medkits and Adrenaline Shots)

### ISSUE THREAD

**Issue by Bit-Glitch33** [CraftPig/sweps_scpsl_consumables#10]
Sometimes randomly, possibly if in a loadout when you spawn, either the entire medkit box besides the zipper and bandage will disappear or the top half will disappear, along when these happen, the models for Adrenaline Shots / Stims will vanish

**Comment by CraftPig** [comment]
This happens if bodygroup modifiers are transfered from swep to swep, usually happens with ARC9's attachment system. So it isn't even really a problem on our end but something could be done to compensate still.
