### ISSUE TITLE
Items lack audio from other player’s perspectives

### ISSUE THREAD

**Issue by TheMasterfulMann** [CraftPig/sweps_scpsl_consumables#2]
There is a very slight auditory issue with the addon, as for both NMRIH consumables, and the SCP. They share the same issue of the audio being inconsistent.

The sound effects for consumption do not play in 3rd person (**only sometimes it plays when consuming the candy bag, making a weird sound in 3rd person**), nor do they play when other players use the items from my POV. Meaning the sounds only play for the person using the items in 1st person. It would help if either there was an option in the settings to enable 3rd person sounds, or if unintentional, just patched out.

That is about all. Thank you for your contributions to the workshop!

**Comment by NNinja1255** [comment]
I am pretty sure the reason to that is because the sound effects come from the viewmodels and are not emitted via EmitSound(). That's why you can only hear them in first person.

**Comment by Aaronek10** [comment]
> I am pretty sure the reason to that is because the sound effects come from the viewmodels and are not emitted via EmitSound(). That's why you can only hear them in first person.


I didn't created SWEPs in first place, i was creating SEF functionality and entities for SCP: SL, but this is good suggestion and i will apply this correction.

(Didn't tested SCP:SL SWEPs outside singleplayer)

**Comment by CraftPig** [comment]
Sounds are baked into the sequences as sound events, so only the owner can hear them. I went with this setup, because I didn't really see the need to put in extra time to edit the audio and create EmitSound entities so its hearable for other players. It's a request ill keep in mind.

**Comment by TheMasterfulMann** [comment]
> Sounds are baked into the sequences as sound events, so only the owner can hear them. I went with this setup, because I didn't really see the need to put in extra time to edit the audio and create EmitSound entities so its hearable for other players. It's a request ill keep in mind.

Oh, alrighty then, and thank you for taking the time to reply!
