### ISSUE TITLE
Not sure if this is intentional

### ISSUE THREAD

**Issue by NNinja1255** [CraftPig/sweps_scpsl_consumables#7]
https://github.com/user-attachments/assets/ea4970ad-13f6-475f-b4d1-fd81cfe53b97

The use of both Anti SCP-207 and SCP-1853 does not poison the player. From the description, it sounded like both Colas would've poisoned. Is this a bug?

**Comment by Badbadalex1** [comment]
neither SCPs are supposed to damage you, quite the opposite actually
Anti-207 heals, not hurts
1843 typically increases stamina usage but since that isn't a thing by default in gmod, it just has no side effects

**Comment by Aaronek10** [comment]
> neither SCPs are supposed to damage you, quite the opposite actually Anti-207 heals, not hurts 1843 typically increases stamina usage but since that isn't a thing by default in gmod, it just has no side effects

There was an issue in SEF system, mainly with Poison status effect. It's fixed and now only code need to include applying Poison effect once you use both, SCP-207 and SCP-1853. Anti SCP-207 wont have any interaction with SCP-1853.
