### ISSUE TITLE
the scp-207 bug

### ISSUE THREAD

**Issue by Mrpurple007** [CraftPig/sweps_scpsl_consumables#8]
when you moving and drink it the buff isn't working, but if you drink it again it will work
if you stand and drink it, buff will work normally

**Comment by Aaronek10** [comment]
Can you show some sort of video to present this bug? This will help in troubleshoting the issue

**Comment by NNinja1255** [comment]
> when you moving and drink it the buff isn't working, but if you drink it again it will work if you stand and drink it, buff will work normally

I've also encountered this issue too.

**Comment by Aaronek10** [comment]
> > when you moving and drink it the buff isn't working, but if you drink it again it will work if you stand and drink it, buff will work normally
> 
> I've also encountered this issue too.

I would like to see video how this happends

**Comment by Mrpurple007** [comment]
i'l try to record and test

**Comment by Mrpurple007** [comment]
this is addon bug

**Comment by Mrpurple007** [comment]
il' type later what addon causing this bug

**Comment by Mrpurple007** [comment]
very strange, maybe this is SEF issue so it's working now
